name = "cf_ai_squirrito"
main = "src/index.ts"
compatibility_date = "2024-09-10"
compatibility_flags = ["nodejs_compat"]

[ai]
binding = "AI"

[durable_objects]
bindings = [{ name = "GEO_MEMORIES", class_name = "GeoMemoryDO" }]

[[migrations]]
tag = "v1-sqlite"
new_sqlite_classes = ["GeoMemoryDO"]
